(function(){
'use strict';
const $=id=>document.getElementById(id),{Simulation,DEFAULTS,VERSION,diffraction,lattice}=window.ZrNb;
let sim=new Simulation(),running=false,active='evolution',selectedCell=null,preset='coupled',snapshots=[],lastFrame=0;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
function rangePaint(){document.querySelectorAll('input[type=range]').forEach(el=>el.style.setProperty('--fill',((Number(el.value)-Number(el.min))/(Number(el.max)-Number(el.min))*100)+'%'));}
document.addEventListener('input',rangePaint);
const MAX_STEPS=2000,colors={free:'#2487d7',trapped:'#d98235',hydride:'#8a68dc',v:'#e15b55',interstitial:'#879b28'};
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
function sizeCanvas(canvas){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return null;const dpr=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);return{ctx,w:rect.width,h:rect.height};}
function switchTab(name){active=name;document.querySelectorAll('[role=tab]').forEach(b=>b.setAttribute('aria-selected',b.id==='tab-'+name?'true':'false'));document.querySelectorAll('[role=tabpanel]').forEach(p=>p.hidden=p.id!==name);if(name!=='evolution')setRunning(false);redraw();}
document.querySelectorAll('[role=tab]').forEach((b,i)=>{b.addEventListener('click',()=>switchTab(b.getAttribute('aria-controls')));b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const btns=Array.from(document.querySelectorAll('[role=tab]'));const j=(i+(e.key==='ArrowRight'?1:-1)+btns.length)%btns.length;btns[j].focus();switchTab(btns[j].getAttribute('aria-controls'));}});});
$('modelLink').onclick=e=>{e.preventDefault();switchTab('learn');};
const beamHints={neutron:'Neutron recoil damage is represented by a random bulk defect source.',proton:'Protons are hydrogen nuclei. This scenario adds local defects and H; profiles and ratios are illustrative.',heavy:'Clustered sources illustrate cascade damage. Beam energy, physical range and electronic stopping are not calculated.',electron:'Illustrative dispersed displacement defects. Electron energy thresholds and irradiation-assisted H release are omitted.'};
function syncControls(){for(const k of ['temperature','hydrogen','radiation','nb','grains','seed','beam'])$(k).value=sim.params[k];updateLabels();}
function updateLabels(){rangePaint();for(const k of ['temperature','hydrogen','radiation','nb'])$(k+'Value').textContent=$(k).value+(k==='temperature'?' °C':k==='nb'?'%':' / 100');$('beamHint').textContent=beamHints[$('beam').value];}
function unselectPreset(){preset='custom';document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('selected'));}
for(const k of ['temperature','hydrogen','radiation'])$(k).addEventListener('input',()=>{sim.setParam(k,Number($(k).value));updateLabels();unselectPreset();updateUI();});
$('beam').onchange=()=>{sim.setParam('beam',$('beam').value);updateLabels();unselectPreset();updateUI();};$('nb').oninput=updateLabels;
function rebuild(params){setRunning(false);sim=new Simulation(params);selectedCell=null;syncControls();drawMicro();updateUI();}
$('rebuild').onclick=()=>{const seed=Number($('seed').value);if(!Number.isInteger(seed)||seed<1||seed>999999){toast('Use an integer seed from 1 to 999999.');$('seed').focus();return;}rebuild({...sim.params,nb:Number($('nb').value),grains:Number($('grains').value),seed});unselectPreset();toast('Sample rebuilt. Step count and history restarted.');};
const presets={baseline:{temperature:300,hydrogen:0,radiation:0,initialH:0},hydrogen:{temperature:150,hydrogen:85,radiation:0,initialH:120},radiation:{temperature:150,hydrogen:0,radiation:75,initialH:0},coupled:{temperature:150,hydrogen:85,radiation:65,initialH:120}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{preset=b.dataset.preset;const sample={seed:sim.params.seed,nb:sim.params.nb,grains:sim.params.grains};rebuild({...DEFAULTS,...sample,...presets[preset]});document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('selected',x===b));toast('Scenario applied. A new run is ready.');});
function setRunning(value){running=value&&sim.tick<MAX_STEPS;$('runStatus').classList.toggle('running',running);$('play').textContent=running?'Ⅱ Pause':'▶ Run';$('runStatus').textContent=(running?'Running':'Paused')+' · step '+sim.tick;}
$('play').onclick=()=>{if(sim.tick>=MAX_STEPS){toast('Reached 2000 steps. Export the record, then reset.');return;}setRunning(!running);};
$('step').onclick=()=>{setRunning(false);sim.step(Math.min(100,MAX_STEPS-sim.tick));drawMicro();updateUI();if(sim.tick===MAX_STEPS)toast('Reached 2000 steps.');};
$('reset').onclick=()=>{rebuild({...sim.params});toast('Restarted with the current conditions.');};
$('anneal').onclick=()=>{sim.setParam('temperature',600);sim.setParam('hydrogen',0);sim.setParam('radiation',0);syncControls();unselectPreset();updateUI();toast('Heating stage ready. Structure and counts are preserved; advance to observe changes.');};
const microView=new MicroView($('microCanvas'),()=>sim,k=>{selectedCell=k;cellInfo();});
function drawMicro(){microView.selected=selectedCell;microView.draw();}
function cellInfo(){const k=selectedCell;$('clearCell').disabled=k===null;if(k===null){$('inspectorTitle').textContent='Select a cell in the map';$('inspectorMeta').textContent='Read exact counts and compare the surrounding 5 × 5 cells.';$('inspectorCounts').innerHTML='';$('cellInfo').textContent='Grain outlines are continuous guides; counts belong to discrete model cells. Marker shapes and offsets separate overlapping species and do not represent atomic positions.';return;}
 const x=k%sim.w,y=Math.floor(k/sim.w),keys=['free','trapped','hydride','v','interstitial'],names=['Mobile H','Trapped H','Hydride H','Vacancies','Interstitials'],totals=Object.fromEntries(keys.map(k=>[k,0]));let n=0;
 for(let yy=Math.max(0,y-2);yy<=Math.min(sim.h-1,y+2);yy++)for(let xx=Math.max(0,x-2);xx<=Math.min(sim.w-1,x+2);xx++){n++;for(const key of keys)totals[key]+=sim[key][yy*sim.w+xx];}
 $('inspectorTitle').textContent=`Cell (${x}, ${y}) · grain ${sim.grain[k]+1}`;$('inspectorMeta').textContent=`${sim.nbMask[k]?'Nb-rich region':'α-Zr region'}${sim.boundary[k]?' · grain-boundary sink cell':''} · step ${sim.tick} · neighbourhood: ${n} cells`;
 $('inspectorCounts').innerHTML=keys.map((key,i)=>`<div class="inspect-${key}"><span>${names[i]}</span><strong>${sim[key][k]}</strong><small>Nearby total: ${totals[key]}</small></div>`).join('');
 $('cellInfo').textContent=`Selected cell: mobile H ${sim.free[k]}, trapped H ${sim.trapped[k]}, hydride H ${sim.hydride[k]}, vacancies ${sim.v[k]}, interstitials ${sim.interstitial[k]}. Counts include hidden layers; neighbourhood totals include the selected cell.`;
}
$('microZoom').oninput=()=>microView.setZoom(Number($('microZoom').value));$('fitMicro').onclick=()=>{microView.reset();rangePaint();};
function mapTool(name){microView.tool=name;$('inspectTool').setAttribute('aria-pressed',name==='inspect');$('panTool').setAttribute('aria-pressed',name==='pan');$('microCanvas').style.cursor=name==='pan'?'grab':'crosshair';}
$('inspectTool').onclick=()=>mapTool('inspect');$('panTool').onclick=()=>mapTool('pan');$('clearCell').onclick=()=>microView.select(null);
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;microView.layers[k]=!microView.layers[k];b.setAttribute('aria-pressed',microView.layers[k]);drawMicro();});
$('allLayers').onclick=()=>{for(const k in microView.layers)microView.layers[k]=true;document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed','true'));drawMicro();};
document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{microView.mode=b.dataset.map;document.querySelectorAll('[data-map]').forEach(el=>el.setAttribute('aria-pressed',el===b));document.querySelectorAll('[data-layer]').forEach(el=>{el.disabled=microView.mode!=='symbols'&&!['grains','nb'].includes(el.dataset.layer);});drawMicro();});
$('findHotspot').onclick=()=>{let best=0,count=-1;for(let k=0;k<sim.n;k++){const value=microView.mode==='defects'?sim.v[k]+sim.interstitial[k]:sim.free[k]+sim.trapped[k]+sim.hydride[k];if(value>count){count=value;best=k;}}if(count===0){toast('No '+(microView.mode==='defects'?'defects':'hydrogen')+' in this sample yet.');return;}microView.select(best);microView.cx=best%sim.w+.5;microView.cy=Math.floor(best/sim.w)+.5;microView.setZoom(3);rangePaint();toast('Selected the highest-count cell; ties use the first grid index.');};
$('singleStep').onclick=()=>{setRunning(false);sim.step(Math.min(1,MAX_STEPS-sim.tick));drawMicro();updateUI();};
function chart(canvas,keys){const c=sizeCanvas(canvas);if(!c)return;const{ctx,w,h}=c,left=40,right=10,top=27,bottom=28,pw=w-left-right,ph=h-top-bottom;const history=sim.history;const now=sim.stats(),data=history[history.length-1].step===now.step?history:history.concat(now);const maxX=Math.max(100,sim.tick),maxY=Math.max(10,...data.map(s=>Math.max(...keys.map(k=>s[k]))))*1.12;ctx.font='10px -apple-system, sans-serif';ctx.textBaseline='middle';
 for(let j=0;j<=3;j++){const yy=top+ph*j/3;ctx.strokeStyle='#e8edf2';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#728195';ctx.textAlign='right';const v=maxY*(1-j/3);ctx.fillText(v>=1000?(v/1000).toFixed(1)+'k':Math.round(v),left-7,yy);}
 for(let j=0;j<=4;j++){ctx.fillStyle='#728195';ctx.textAlign=j===4?'right':'center';ctx.fillText(Math.round(maxX*j/4),left+pw*j/4,h-14);}ctx.textAlign='left';ctx.fillText('Count',0,8);
 for(const key of keys){ctx.strokeStyle=colors[key];ctx.lineWidth=1.8;ctx.beginPath();data.forEach((s,i)=>{const xx=left+s.step/maxX*pw,yy=top+ph-s[key]/maxY*ph;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);});ctx.stroke();}ctx.fillStyle='#728195';ctx.textAlign='right';ctx.fillText('Step',w-1,h-6);}
function updateUI(){const s=sim.stats();$('totalH').textContent=s.totalH.toLocaleString();$('trappedCount').textContent=s.trapped.toLocaleString();$('hydrideCount').textContent=s.hydride.toLocaleString();$('defectCount').textContent=s.v.toLocaleString()+' / '+s.interstitial.toLocaleString();$('runStatus').textContent=(running?'Running':'Paused')+' · step '+s.step;cellInfo();chart($('hydrogenChart'),['free','trapped','hydride']);chart($('defectChart'),['v','interstitial']);let text;
 if(!s.step)text='Advance 100 steps to observe H entering at the left boundary and defects forming inside.';
 else if(sim.params.temperature>=500&&sim.params.hydrogen===0&&sim.params.radiation===0)text=`External sources are off. Total H remains ${s.totalH}, while mobile, trapped and precipitated reservoirs exchange H. Heating also promotes defect recovery; surface H release is omitted.`;
 else if(s.hydride>0)text=`Local H accumulation has triggered precipitation in ${s.hydrideCells} cells. Purple markers follow illustrative grain orientations; no stress-driven morphology is predicted.`;
 else if(s.trapped>0)text=`There are ${s.trapped} trapped H tracers. Compare orange markers with vacancies, grain boundaries and Nb-rich regions to explore enrichment.`;
 else if(s.generated>0)text=`${s.generated} defect pairs have formed and ${s.recombined} pairs have recombined. Production, recombination and grain-boundary absorption determine the remaining counts.`;
 else text='Without external sources, this initial model structure stays unchanged. Use it as a comparison scenario.';$('observation').textContent=text;}
function download(name,body,type){const url=URL.createObjectURL(new Blob(['\uFEFF',body],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
$('exportJSON').onclick=()=>download(`zrnb-model-step-${sim.tick}.json`,JSON.stringify({...sim.export(),snapshots},null,2),'application/json');
$('exportCSV').onclick=()=>{const s=sim.stats(),data=sim.history.at(-1).step===s.step?sim.history:sim.history.concat(s);const keys=['step','free','trapped','hydride','totalH','v','interstitial','injected','generated','recombined','sunkV','sunkI'];let out='# Educational model; uncalibrated counts; NOT experimental data\n# Version '+VERSION+'; seed '+sim.params.seed+'\n# Initial parameters '+JSON.stringify(sim.initialParams)+'\n# Current parameters '+JSON.stringify(sim.params)+'\n# Parameter changes '+JSON.stringify(sim.changes)+'\n'+keys.join(',')+'\n'+data.map(x=>keys.map(k=>x[k]).join(',')).join('\n');download(`zrnb-teaching-history-${sim.tick}.csv`,out,'text/csv;charset=utf-8');};
$('snapshot').onclick=()=>{if(snapshots.length>=6){toast('Up to 6 snapshots can be stored. Export the full record before clearing.');return;}snapshots.push({initialParams:{...sim.initialParams},params:{...sim.params},stats:sim.stats(),changes:sim.changes.map(c=>({...c}))});renderSnapshots();toast('Snapshot saved.');};
function renderSnapshots(){$('comparison').hidden=!snapshots.length;const names={neutron:'Neutrons',proton:'Protons',heavy:'Heavy ions',electron:'Electrons'};$('snapshotRows').innerHTML=snapshots.map(x=>`<tr><td>${x.params.temperature} °C · H${x.params.hydrogen} / R${x.params.radiation} · ${names[x.params.beam]}<br><small>seed ${x.params.seed} · ${x.params.grains} grains · Nb ${x.params.nb}%${x.changes.length?' · staged protocol':''}</small></td>${['step','totalH','trapped','hydride','v'].map(k=>'<td>'+x.stats[k]+'</td>').join('')}</tr>`).join('');}
$('clearSnapshots').onclick=()=>{snapshots=[];renderSnapshots();};
let rotation={x:-.38,y:.65},targetRotation={...rotation},zoom=1,targetZoom=1,drag=null;
function settleView(){if(reducedMotion.matches){rotation={...targetRotation};zoom=targetZoom;drawCrystal();}rangePaint();}
function crystalData(){const mode=$('lattice').value,atoms=[],seen=new Set();const add=(x,y,z,type,layer=0)=>{const key=[x,y,z,type].map(v=>typeof v==='number'?v.toFixed(5):v).join('/');if(!seen.has(key)){seen.add(key);atoms.push({x,y,z,type,layer});}};let a,c;
 if(mode==='hcp'){a=lattice.zr.a;c=lattice.zr.c;for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++)for(let k=0;k<=1;k++)for(let b=0;b<2;b++){const u=i+b*2/3,v=j+b/3;add(a*(u-v/2),a*Math.sqrt(3)/2*v,c*(k+b/2),'metal',b);}if($('showH').checked){const z=c/4-a*a/(3*c);for(let i=-1;i<=1;i++)add(i*a+a/2,a*Math.sqrt(3)/6,z,'H');}}
 else{a=mode==='bcc'?lattice.nb.a:lattice.hydride.a;c=a;for(let i=0;i<=2;i++)for(let j=0;j<=2;j++)for(let k=0;k<=2;k++){add(i*a,j*a,k*a,'metal');if(i<2&&j<2&&k<2){if(mode==='bcc')add((i+.5)*a,(j+.5)*a,(k+.5)*a,'metal',1);else{add((i+.5)*a,(j+.5)*a,k*a,'metal',1);add((i+.5)*a,j*a,(k+.5)*a,'metal',1);add(i*a,(j+.5)*a,(k+.5)*a,'metal',1);}}}
 if(mode==='fcc'){// Add face sites on the three outermost faces to complete the finite crystal.
 for(let i=0;i<2;i++)for(let j=0;j<2;j++){add((i+.5)*a,(j+.5)*a,2*a,'metal',1);add((i+.5)*a,2*a,(j+.5)*a,'metal',1);add(2*a,(i+.5)*a,(j+.5)*a,'metal',1);}}
 if($('showH').checked){if(mode==='bcc')[[.5,.25,0],[1,.5,.25],[.25,1,.5]].forEach(p=>add(...p.map(x=>x*a),'H'));else{let count=0;for(const x of [.25,.75])for(const y of [.25,.75])for(const z of [.25,.75])if(count++<6)add(x*a,y*a,z*a,'H');}}}
 const bounds=['x','y','z'].map(key=>{const vals=atoms.filter(p=>p.type==='metal').map(p=>p[key]);return[(Math.min(...vals)+Math.max(...vals))/2,Math.max(...vals)-Math.min(...vals)];});atoms.forEach(p=>{p.x-=bounds[0][0];p.y-=bounds[1][0];p.z-=bounds[2][0];});return{atoms,a,c,mode,span:Math.max(...bounds.map(x=>x[1]))};}
function crystalText(){const mode=$('lattice').value;const content={hcp:['α-Zr · hexagonal close-packed','Alternating A and B layers appear in two shades of blue. Orange spheres illustrate H at selected tetrahedral interstitial sites; they are not H₂ molecules or a specified concentration.','a = 0.32324 nm<br>c = 0.51472 nm<br>c/a = '+(lattice.zr.c/lattice.zr.a).toFixed(3)],bcc:['Nb · body-centred cubic','Metal atoms occupy cube corners and centres. This is a pure Nb reference lattice; actual Nb-rich phases contain other elements. Orange spheres mark selected tetrahedral sites.','a = 0.33000 nm<br>Nearest neighbours = 8'],fcc:['δ hydride · FCC metal sublattice','Zr occupies cube corners and face centres. Six of eight tetrahedral H sites are shown in one cell to illustrate ZrH₁.₅ occupancy. Actual δ-phase composition and disorder depend on conditions.','a = 0.47776 nm<br>Metal sublattice = FCC<br>Illustrative H occupancy']};$('crystalTitle').textContent=content[mode][0];$('crystalDescription').textContent=content[mode][1];$('latticeNumbers').innerHTML=content[mode][2];}
function drawCrystal(){const c=sizeCanvas($('crystalCanvas'));if(!c)return;const{ctx,w,h}=c,data=crystalData(),scale=Math.min(w*.57,h*.7)/data.span*zoom;const cy=Math.cos(rotation.y),sy=Math.sin(rotation.y),cx=Math.cos(rotation.x),sx=Math.sin(rotation.x);
 const project=p=>{const xx=p.x*cy+p.y*sy,yy=-p.x*sy+p.y*cy;return{x:w*.5+xx*scale,y:h*.48+(yy*sx-p.z*cx)*scale,z:yy*cx+p.z*sx};};
 const backdrop=ctx.createRadialGradient(w*.5,h*.4,10,w*.5,h*.5,w*.7);backdrop.addColorStop(0,'#ffffff');backdrop.addColorStop(1,'#eaf2f6');ctx.fillStyle=backdrop;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#ebf0f4';ctx.lineWidth=1;for(let i=0;i<7;i++){const yy=h*.64+i*12;ctx.beginPath();ctx.moveTo(w*.15,yy);ctx.lineTo(w*.85,yy);ctx.stroke();}
 if($('showBonds').checked){ctx.lineWidth=.8;for(let i=0;i<data.atoms.length;i++){const a=data.atoms[i];if(a.type!=='metal')continue;for(let j=i+1;j<data.atoms.length;j++){const b=data.atoms[j];if(b.type!=='metal')continue;const distance=Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);const threshold=data.a*(data.mode==='hcp'?1.04:data.mode==='bcc'?.89:.73);if(distance<threshold){const p=project(a),q=project(b);ctx.strokeStyle='#819daf42';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}}}
 const points=data.atoms.map(a=>({...a,p:project(a)})).sort((a,b)=>a.p.z-b.p.z);for(const a of points){const r=(a.type==='H'?4.1:7.5)*Math.min(1.25,zoom)*(w<450?.8:1),p=a.p;const col=a.type==='H'?'#ee9e47':data.mode==='bcc'?(a.layer?'#55b5a9':'#25897f'):data.mode==='fcc'?(a.layer?'#9e8bd5':'#7159ab'):(a.layer?'#73b7d9':'#377da6');const gradient=ctx.createRadialGradient(p.x-r*.3,p.y-r*.3,r*.05,p.x,p.y,r);gradient.addColorStop(0,a.type==='H'?'#ffe0a5':'#dbeefa');gradient.addColorStop(.4,col);gradient.addColorStop(1,a.type==='H'?'#b56c2d':data.mode==='bcc'?'#19695f':data.mode==='fcc'?'#51407e':'#255575');ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(p.x,p.y,r,0,2*Math.PI);ctx.fill();}
 const origin={x:0,y:0,z:0};const axes=[['a₁',{x:data.a,y:0,z:0},'#64869b'],['a₂',{x:data.mode==='hcp'?-data.a/2:0,y:data.mode==='hcp'?data.a*Math.sqrt(3)/2:data.a,z:0},'#64869b'],['c',{x:0,y:0,z:data.c},'#136b69']];const o=project(origin);ctx.font='12px -apple-system,sans-serif';for(const[label,v,color]of axes){const end=project(v),x0=55,y0=h-45,ex=x0+(end.x-o.x)*.28,ey=y0+(end.y-o.y)*.28;ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(ex,ey);ctx.stroke();ctx.fillStyle=color;ctx.fillText(label,ex+4,ey+2);}
 ctx.fillStyle='#6c7e8d';ctx.font='11px -apple-system,sans-serif';ctx.textAlign='right';ctx.fillText('Sphere sizes are illustrative',w-20,h-18);ctx.textAlign='left';}
$('lattice').onchange=()=>{crystalText();drawCrystal();};['showBonds','showH'].forEach(k=>$(k).onchange=drawCrystal);
$('rotateLeft').onclick=()=>{targetRotation.y-=.25;settleView();};$('rotateUp').onclick=()=>{targetRotation.x+=.2;settleView();};$('homeView').onclick=()=>{targetRotation={x:-.38,y:.65};targetZoom=1;$('zoom').value=100;settleView();};$('zoom').oninput=()=>{targetZoom=Number($('zoom').value)/100;settleView();};
$('crystalCanvas').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};$('crystalCanvas').setPointerCapture(e.pointerId);};$('crystalCanvas').onpointermove=e=>{if(!drag)return;targetRotation.y+=(e.clientX-drag.x)*.008;targetRotation.x+=(e.clientY-drag.y)*.008;drag={x:e.clientX,y:e.clientY};settleView();};$('crystalCanvas').onpointerup=()=>drag=null;$('crystalCanvas').onpointercancel=()=>drag=null;$('crystalCanvas').addEventListener('wheel',e=>{e.preventDefault();targetZoom=Math.max(.65,Math.min(1.5,targetZoom-e.deltaY*.001));$('zoom').value=Math.round(targetZoom*100);settleView();},{passive:false});
let xrdPeaks=[];
function xrdParams(){return{strain:Number($('strain').value),size:Number($('domainSize').value),microstrain:Number($('microstrain').value),nb:$('xrdNb').checked,hydride:$('xrdHydride').checked};}
function drawXRD(){rangePaint();const params=xrdParams();$('strainValue').textContent=params.strain.toFixed(2)+'%';$('domainSizeValue').textContent=params.size+' nm';$('microstrainValue').textContent=params.microstrain.toFixed(2)+'%';xrdPeaks=diffraction(params);$('peakRows').innerHTML=xrdPeaks.map(p=>`<tr><td>${p.phase}</td><td>(${p.hkl})</td><td>${p.d.toFixed(5)}</td><td>${p.twoTheta.toFixed(2)}</td><td>${p.fwhm.toFixed(3)}</td></tr>`).join('');const c=sizeCanvas($('xrdCanvas'));if(!c)return;const{ctx,w,h}=c,left=48,right=18,top=40,bottom=43,pw=w-left-right,ph=h-top-bottom;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.font='10px -apple-system,sans-serif';ctx.textBaseline='middle';
 for(let j=0;j<=4;j++){const yy=top+j*ph/4;ctx.strokeStyle='#e7edf2';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#768698';ctx.textAlign='right';ctx.fillText(Math.round(120*(1-j/4)),left-8,yy);}
 for(let a=30;a<=80;a+=10){const xx=left+(a-25)/60*pw;ctx.fillStyle='#768698';ctx.textAlign='center';ctx.fillText(a,xx,h-24);}ctx.fillStyle='#617287';ctx.textAlign='left';ctx.fillText('Intensity / a.u.',left,18);ctx.textAlign='right';ctx.fillText('2θ / °',w-16,h-8);
 const phaseColor={'α-Zr':'#2487d7','Nb':'#27b4a3','δ-ZrHₓ':'#d98235'};for(const phase of Object.keys(phaseColor)){const peaks=xrdPeaks.filter(p=>p.phase===phase);if(!peaks.length)continue;ctx.strokeStyle=phaseColor[phase];ctx.lineWidth=1.6;ctx.beginPath();for(let i=0;i<=pw*2;i++){const a=25+i/(pw*2)*60;const value=peaks.reduce((s,p)=>s+p.intensity*Math.exp(-4*Math.log(2)*((a-p.twoTheta)/p.fwhm)**2),0);const xx=left+i/2,yy=top+ph-value/120*ph;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.stroke();}
 const labels=xrdPeaks.filter(p=>p.intensity>=55);ctx.font='10px -apple-system,sans-serif';for(let i=0;i<labels.length;i++){const p=labels[i],xx=left+(p.twoTheta-25)/60*pw;ctx.fillStyle=phaseColor[p.phase];ctx.textAlign='center';ctx.fillText(p.phase+' '+p.hkl,xx,top+ph-p.intensity/120*ph-14-(i%2)*5);}
 $('xrdReadout').textContent=`Uniform strain: ${params.strain.toFixed(2)}%. Coherent domain: ${params.size} nm. Peak positions reflect plane spacing; widths include size, microstrain and instrument terms. Hover or tap to inspect a reference peak.`;}
for(const k of ['strain','domainSize','microstrain'])$(k).oninput=drawXRD;for(const k of ['xrdNb','xrdHydride'])$(k).onchange=drawXRD;
$('resetXRD').onclick=()=>{$('strain').value=0;$('domainSize').value=80;$('microstrain').value=.1;$('xrdNb').checked=true;$('xrdHydride').checked=true;drawXRD();};
function readXRD(e){const rect=$('xrdCanvas').getBoundingClientRect(),angle=25+(e.clientX-rect.left-48)/(rect.width-66)*60;if(angle<25||angle>85||!xrdPeaks.length)return;const p=xrdPeaks.reduce((a,b)=>Math.abs(a.twoTheta-angle)<Math.abs(b.twoTheta-angle)?a:b);$('xrdReadout').textContent=`Nearest reference peak: ${p.phase} (${p.hkl}) · 2θ = ${p.twoTheta.toFixed(2)}° · d = ${p.d.toFixed(5)} nm · FWHM = ${p.fwhm.toFixed(3)}°. Intensities are teaching weights, not phase-fraction measurements.`;}
$('xrdCanvas').onmousemove=readXRD;$('xrdCanvas').onclick=readXRD;
function redraw(){if(active==='evolution'){drawMicro();updateUI();}else if(active==='crystal'){crystalText();drawCrystal();}else if(active==='xrd')drawXRD();}
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(redraw,100);});document.addEventListener('visibilitychange',()=>{if(document.hidden)setRunning(false);});
let viewFrame=0;
function animate(now){const dt=Math.min(50,now-viewFrame);viewFrame=now;if(active==='crystal'&&(Math.abs(rotation.x-targetRotation.x)+Math.abs(rotation.y-targetRotation.y)+Math.abs(zoom-targetZoom)>.0001)){const ease=reducedMotion.matches?1:1-Math.exp(-dt/75);rotation.x+=(targetRotation.x-rotation.x)*ease;rotation.y+=(targetRotation.y-rotation.y)*ease;zoom+=(targetZoom-zoom)*ease;drawCrystal();}if(now-lastFrame>50){lastFrame=now;if(running){sim.step(Math.min(Number($('speed').value),MAX_STEPS-sim.tick));if(sim.tick>=MAX_STEPS)setRunning(false);drawMicro();updateUI();}}requestAnimationFrame(animate);}
syncControls();crystalText();redraw();requestAnimationFrame(animate);
// Read-only inspection interface used by tests and advanced learners.
window.ZrNbApp={get simulation(){return sim;},get active(){return active;},get snapshots(){return snapshots;},switchTab,redraw};
})();
