/* Rendering and inspection only. Never mutates the simulation or its RNG. */
window.MicroView=class {
 constructor(canvas,getSim,onSelect){this.canvas=canvas;this.getSim=getSim;this.onSelect=onSelect;this.zoom=1;this.cx=36;this.cy=22;this.selected=null;this.hover=null;this.mode='symbols';this.layers={grains:true,nb:true,free:true,trapped:true,hydride:true,v:true,interstitial:true};this.tool='inspect';this.cache=null;this.drag=null;
 canvas.addEventListener('pointerdown',e=>{this.drag={x:e.clientX,y:e.clientY,cx:this.cx,cy:this.cy,moved:false};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(this.drag&&this.tool==='pan'){const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.drag.moved ||=Math.hypot(dx,dy)>3;this.cx=this.drag.cx-dx/this.b.sx;this.cy=this.drag.cy-dy/this.b.sy;this.clamp();this.draw();return;}this.hover=this.hit(e);this.draw();this.tooltip(e);});
 canvas.addEventListener('pointerup',e=>{if(this.drag&&!this.drag.moved&&this.tool==='inspect')this.select(this.hit(e));this.drag=null;});
 canvas.addEventListener('pointercancel',()=>this.drag=null);canvas.addEventListener('pointerleave',()=>{this.hover=null;document.getElementById('microTip').hidden=true;this.draw();});
 canvas.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();this.setZoom(this.zoom*Math.exp(-e.deltaY*.002));},{passive:false});
 canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','+','-','Escape'].includes(e.key)){e.preventDefault();if(e.key==='+')return this.setZoom(this.zoom+.5);if(e.key==='-')return this.setZoom(this.zoom-.5);if(e.key==='Escape')return this.select(null);let k=this.selected??Math.floor(this.getSim().n/2),x=k%72,y=Math.floor(k/72);if(e.key==='ArrowLeft')x--;if(e.key==='ArrowRight')x++;if(e.key==='ArrowUp')y--;if(e.key==='ArrowDown')y++;this.select(Math.max(0,Math.min(43,y))*72+Math.max(0,Math.min(71,x)));this.cx=x+.5;this.cy=y+.5;this.clamp();this.draw();}});
 }
 clamp(){const s=this.getSim(),hx=s.w/this.zoom/2,hy=s.h/this.zoom/2;this.cx=Math.max(hx,Math.min(s.w-hx,this.cx));this.cy=Math.max(hy,Math.min(s.h-hy,this.cy));}
 setZoom(z){if(this.zoom===1&&this.selected!==null){this.cx=this.selected%72+.5;this.cy=Math.floor(this.selected/72)+.5;}this.zoom=Math.max(1,Math.min(5,z));this.clamp();document.getElementById('microZoom').value=this.zoom;document.getElementById('microZoom').style.setProperty('--fill',((this.zoom-1)/4*100)+'%');document.getElementById('microZoomValue').textContent=this.zoom.toFixed(1)+'×';this.draw();}
 reset(){this.cx=36;this.cy=22;this.setZoom(1);}
 select(k){this.selected=k;this.onSelect(k);this.draw();}
 hit(e){if(!this.b)return null;const r=this.canvas.getBoundingClientRect(),b=this.b,px=e.clientX-r.left,py=e.clientY-r.top;if(px<b.left||px>b.left+b.w||py<b.top||py>b.top+b.h)return null;const x=Math.floor((px-b.left)/b.sx+b.x0),y=Math.floor((py-b.top)/b.sy+b.y0);return Math.min(43,y)*72+Math.min(71,x);}
 tooltip(e){const tip=document.getElementById('microTip');if(this.hover===null){tip.hidden=true;return;}const s=this.getSim(),k=this.hover;tip.textContent=`Cell ${k%72}, ${Math.floor(k/72)} · H ${s.free[k]+s.trapped[k]+s.hydride[k]} · Defects ${s.v[k]+s.interstitial[k]}`;tip.hidden=false;const r=this.canvas.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.width-220,e.clientX-r.left+12))+'px';tip.style.top=Math.max(8,e.clientY-r.top-35)+'px';}
 geometry(s){if(this.cache===s)return;this.cache=s;this.polygons=s.sites.map((site,i)=>{let poly=[[0,0],[72,0],[72,44],[0,44]];s.sites.forEach((other,j)=>{if(i===j)return;const ax=site.x+.5,ay=site.y+.5,bx=other.x+.5,by=other.y+.5,nx=bx-ax,ny=by-ay,c=(bx*bx+by*by-ax*ax-ay*ay)/2,out=[];for(let k=0;k<poly.length;k++){const a=poly[k],b=poly[(k+1)%poly.length],da=a[0]*nx+a[1]*ny-c,db=b[0]*nx+b[1]*ny-c;if(da<=0)out.push(a);if((da<=0)!==(db<=0)){const t=da/(da-db);out.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);}}poly=out;});return poly;});}
 draw(){const canvas=this.canvas,r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}const c=canvas.getContext('2d'),w=r.width,h=r.height,s=this.getSim();c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);c.fillStyle='#091c2b';c.fillRect(0,0,w,h);const left=25,top=18,pw=w-43,ph=h-47,sx=pw/72*this.zoom,sy=ph/44*this.zoom,x0=this.cx-36/this.zoom,y0=this.cy-22/this.zoom;this.b={left,top,w:pw,h:ph,sx,sy,x0,y0};document.querySelector('.surface-label').hidden=x0>.01;const X=x=>left+(x-x0)*sx,Y=y=>top+(y-y0)*sy;this.geometry(s);c.save();c.beginPath();c.rect(left,top,pw,ph);c.clip();
 const palette=['#203c51','#1a3347','#29485b','#20384b','#234558','#1d3d50','#2b4656','#25394e','#1c4053'];
 this.polygons.forEach((poly,j)=>{if(!poly.length)return;c.beginPath();poly.forEach(([x,y],i)=>i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y)));c.closePath();c.fillStyle=this.layers.grains?palette[j%palette.length]:'#172f41';c.fill();if(this.layers.grains){c.strokeStyle='#9fb7c16b';c.lineWidth=1.1;c.stroke();c.save();c.clip();const site=s.sites[j];c.translate(X(site.x+.5),Y(site.y+.5));c.rotate(site.angle);c.strokeStyle='#9fbbc50b';c.lineWidth=1;for(let n=-1200;n<1200;n+=16){c.beginPath();c.moveTo(-1500,n);c.lineTo(1500,n);c.stroke();}c.restore();}});
 // Nb outlines follow the actual discrete region mask, not an invented phase shape.
 if(this.layers.nb){c.fillStyle='#1c91897d';for(let k=0;k<s.n;k++){if(!s.nbMask[k])continue;const x=k%72,y=Math.floor(k/72);c.fillRect(X(x),Y(y),sx+.2,sy+.2);}c.strokeStyle='#66e2c9';c.lineWidth=1.2;c.beginPath();for(let k=0;k<s.n;k++){if(!s.nbMask[k])continue;const x=k%72,y=Math.floor(k/72),a=X(x),b=Y(y);if(x===0||!s.nbMask[k-1]){c.moveTo(a,b);c.lineTo(a,b+sy);}if(x===71||!s.nbMask[k+1]){c.moveTo(a+sx,b);c.lineTo(a+sx,b+sy);}if(y===0||!s.nbMask[k-72]){c.moveTo(a,b);c.lineTo(a+sx,b);}if(y===43||!s.nbMask[k+72]){c.moveTo(a,b+sy);c.lineTo(a+sx,b+sy);}}c.stroke();}
 const density=this.mode!=='symbols',values=density?Array.from({length:s.n},(_,k)=>this.mode==='hydrogen'?s.free[k]+s.trapped[k]+s.hydride[k]:s.v[k]+s.interstitial[k]):[],max=density?Math.max(1,...values):1;
 if(density){for(let k=0;k<s.n;k++){if(!values[k])continue;const t=Math.log1p(values[k])/Math.log1p(max);c.fillStyle=this.mode==='hydrogen'?`rgba(74,192,255,${.15+.8*t})`:`rgba(255,117,108,${.15+.8*t})`;c.fillRect(X(k%72),Y(Math.floor(k/72)),sx+.1,sy+.1);}}
 else for(let k=0;k<s.n;k++){const xx=X(k%72+.5),yy=Y(Math.floor(k/72)+.5);if(xx<left-sx||xx>left+pw+sx||yy<top-sy||yy>top+ph+sy)continue;const u=Math.min(2.4,Math.sqrt(this.zoom)),ox=sx*.23,oy=sy*.23;
 if(this.layers.hydride&&s.hydride[k]){c.save();c.translate(xx,yy);c.rotate(s.sites[s.grain[k]].angle);const len=Math.min(sx*.78,3+Math.sqrt(s.hydride[k])*1.3)*1.2;c.fillStyle='#c0a1ff';c.strokeStyle='#f0dcff';c.lineWidth=.6;c.beginPath();c.moveTo(-len,0);c.lineTo(0,-1.8*u);c.lineTo(len,0);c.lineTo(0,1.8*u);c.closePath();c.fill();c.stroke();c.restore();}
 if(this.layers.free&&s.free[k]){c.fillStyle='#67d2ff';const count=Math.min(3,s.free[k]);for(let j=0;j<count;j++){const x=xx-ox+((j%2)*1.8-1)*u,y=yy-oy+(j===2?2:0)*u;c.beginPath();c.arc(x,y,1.7*u,0,Math.PI*2);c.fill();}}
 if(this.layers.trapped&&s.trapped[k]){c.fillStyle='#ffc15b';c.strokeStyle='#382512';c.lineWidth=.8;c.beginPath();c.rect(xx+ox-2*u,yy-oy-2*u,4*u,4*u);c.fill();c.stroke();}
 if(this.layers.v&&s.v[k]){c.strokeStyle='#ff8279';c.lineWidth=1.4*u;c.beginPath();c.arc(xx-ox,yy+oy,2.2*u,0,Math.PI*2);c.stroke();}
 if(this.layers.interstitial&&s.interstitial[k]){c.strokeStyle='#e2f48a';c.lineWidth=1.5*u;c.beginPath();c.moveTo(xx+ox-2.6*u,yy+oy);c.lineTo(xx+ox+2.6*u,yy+oy);c.moveTo(xx+ox,yy+oy-2.6*u);c.lineTo(xx+ox,yy+oy+2.6*u);c.stroke();}}
 if(this.zoom>=3){c.strokeStyle='#b7d4e11a';c.lineWidth=.5;c.beginPath();for(let x=Math.ceil(x0);x<x0+72/this.zoom;x++){c.moveTo(X(x),top);c.lineTo(X(x),top+ph);}for(let y=Math.ceil(y0);y<y0+44/this.zoom;y++){c.moveTo(left,Y(y));c.lineTo(left+pw,Y(y));}c.stroke();}
 for(const [k,selected] of [[this.hover,false],[this.selected,true]])if(k!==null){const x=k%72,y=Math.floor(k/72);c.fillStyle=selected?'#ffffff18':'#ffffff0d';c.fillRect(X(x),Y(y),sx,sy);c.strokeStyle=selected?'#fff':'#ffffff80';c.lineWidth=selected?2:1;c.strokeRect(X(x),Y(y),sx,sy);if(selected){c.setLineDash([3,3]);c.strokeStyle='#ffffff50';c.strokeRect(X(Math.max(0,x-2)),Y(Math.max(0,y-2)),(Math.min(72,x+3)-Math.max(0,x-2))*sx,(Math.min(44,y+3)-Math.max(0,y-2))*sy);c.setLineDash([]);}}
 c.restore();c.font='10px -apple-system,sans-serif';c.fillStyle='#a9c5d6';c.fillText(`VIEW ${this.zoom.toFixed(1)}×`,left,h-10);c.textAlign='right';c.fillText(density?`Local count · log colour scale · 0–${max}`:(w<500?'Symbols = presence, not count':'Symbols show presence; inspect a cell for exact counts'),w-18,h-10);c.textAlign='left';
 document.getElementById('densityKey').hidden=!density;document.getElementById('densityKey').textContent=density?`${this.mode==='hydrogen'?'Total H':'Total defects'} per cell · colour scale auto-ranges: 0–${max} (log). Layer filters do not alter this sum.`:'';
 }
};
