const assert=require('node:assert/strict');
const {Simulation,diffraction}=require('../engine.js');
function balance(s){const x=s.stats();assert.equal(x.totalH,x.injected,'H conservation');assert.equal(x.v+x.recombined+x.sunkV,x.generated,'vacancy bookkeeping');assert.equal(x.interstitial+x.recombined+x.sunkI,x.generated,'interstitial bookkeeping');for(const key of ['free','trapped','hydride','v','interstitial'])assert(s[key].every(v=>Number.isInteger(v)&&v>=0),key+' nonnegative integers');assert(s.hydride.every(x=>x%3===0),'whole packets');}
for(const beam of ['neutron','proton','heavy','electron']){const s=new Simulation({beam,hydrogen:90,radiation:90,temperature:150});s.step(300);balance(s);const before=s.stats();s.setParam('hydrogen',0);s.setParam('radiation',0);s.setParam('temperature',600);s.step(300);balance(s);assert.equal(s.stats().totalH,before.totalH);assert.equal(s.stats().generated,before.generated);console.log(beam,s.stats());}
const a=new Simulation({seed:47}),b=new Simulation({seed:47});a.step(50);b.step(50);assert.deepEqual(a.export(),b.export(),'seed reproducibility');
const clean=new Simulation({initialH:0,hydrogen:0,radiation:0});clean.step(100);assert.equal(clean.stats().totalH,0);assert.equal(clean.stats().generated,0);balance(clean);
const neutron=new Simulation({initialH:0,hydrogen:0,radiation:60,beam:'neutron'}),proton=new Simulation({initialH:0,hydrogen:0,radiation:60,beam:'proton'});neutron.step(50);proton.step(50);assert.equal(neutron.stats().totalH,0);assert(proton.stats().totalH>0);
const get=(params={})=>diffraction(params).find(x=>x.phase==='α-Zr'&&x.hkl==='101');const ref=get();assert(get({strain:.5}).twoTheta<ref.twoTheta);assert(get({strain:-.5}).twoTheta>ref.twoTheta);assert(get({size:10}).fwhm>get({size:200}).fwhm);assert(get({microstrain:.4}).fwhm>get({microstrain:0}).fwhm);assert(!diffraction({hydride:false,nb:false}).some(p=>p.phase!=='α-Zr'));assert(ref.twoTheta>36&&ref.twoTheta<37);
const precip=new Simulation({temperature:100,hydrogen:100,radiation:0});precip.step(700);balance(precip);assert(precip.stats().hydride>0,'precipitation reachable');
console.log('PASS: mass balances, thermal history, source distinctions, reproducibility, XRD relations, precipitation.');

const staged=new Simulation({seed:902,temperature:80,hydrogen:50});staged.step(42);staged.setParam('temperature',450);staged.setParam('hydrogen',0);staged.step(81);const saved=staged.export();const replay=new Simulation(saved.initialParams);for(const change of saved.changes){replay.step(change.step-replay.tick);replay.setParam(change.key,change.value);}replay.step(saved.stats.step-replay.tick);assert.deepEqual(replay.export(),saved,'exported protocol replay');console.log('PASS: replay from initial parameters and staged changes.');
